plugins:
  - rubocop-rspec

AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 3.2
  Exclude:
    - "bin/**/*"
    - "vendor/**/*"

Layout/LineLength:
  Max: 120

RSpec/ExampleLength:
  Max: 15

Style/StringLiterals:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

RSpec/SpecFilePathFormat:
  Enabled: false

Gemspec/DevelopmentDependencies:
  Enabled: false

Gemspec/RequiredRubyVersion:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false
